version: '3'

networks:
    nginx-php-mysql:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: public
        ports:
            - "8090:80"
        volumes:
            - ./:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-service
            - mysql-service
        networks:
            - nginx-php-mysql

    # php
    php-service:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php-container
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/project
        networks:
            - nginx-php-mysql

    # mysql
    mysql-service:
        image: mysql:latest
        container_name: mysql-container
        ports:
            - "4306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_PASSWORD: root
        networks:
            - nginx-php-mysql